package com.drools.model.sys;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * SysDictDetail generated by hbm2java
 */
@Data
@Table(name = "sys_dict_detail" )
public class SysDictDetail  {
	@Id
	@Column(name = "id")
	private Long id;//主键
	private Long sdmId;
	private String sdmCode;
	private String sddCode;
	private String sddName;
	private String sddValue1;
	private String sddValue2;
	private String sddValue3;
	private String sddLogic;
	private Integer sddSeq;
	private String sddRemark; 

}
