package com.drools.model.sys;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * SysDictMain generated by hbm2java
 */
@Data
@Table(name = "sys_dict_main" )
public class SysDictMain{
	@Id
	@Column(name = "id")
	private Long id;//主键
	private String sdmCode;
	private String sdmName;
	private String sdmRemark;

}
