package rules;
import com.stu.drools.model.fact.RuleExecutionResult;
global RuleExecutionResult _result;
import com.stu.drools.model.fact.Claim;
import java.lang.String;
import java.util.Map;
import java.util.List;
/*
优先级大小，数字越大，优先级越高
// 数字num为大于等于0的正整数
// 默认为0
// 规则执行顺序按照优先级从大到小执行
// 同优先级随机顺序
// 不设置默认优先级为 0
*/
rule "test-salience1"
    salience 1
when
then
    System.out.println("salience1 执行。。。。");
end

rule "test-salience2"
    salience 2
when
then
    System.out.println("salience2 执行。。。。");
end

rule "test-salience3"
when
then
    System.out.println("salience3 执行。。。。");
end
